### ISSUE TITLE
.bashrc or similar (.jujurc?)

### ISSUE THREAD

**Issue by philrosenberg** [fsquillace/juju#78]
Hi
First I wanted to say juju is excllent. Just installed it on a machine I don't have root access on followed by installation of wine and am about to install some development resources too.
I have just noticed though that on entry juju does not run my .bashrc file. But then if I run bash it does. Actually that might be a good thing as it avoids potential clashes between juju and the host OS. Perhaps, however a .jujurc file or similar would be good to do that job?

I'm not a huge linux guru or anything so I'm sure you have a much better idea about the best way to do this which is perhaps better than the above.

Phil

**Comment by fsquillace** [comment]
Hi Phil,
The reason why it does not source your .bashrc file is because juju runs the terminal as sh --login as this allow to keep things a bit more isolated. This will first run /et/profile and then ~/.profile. So, you can still run your .bashrc by changing accordingly one of this files.
For some OS (like Ubuntu) the /etc/profile is written in order to run .bashrc file directly.
For more information: http://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html#Bash-Startup-Files

There is no plan to include a dedicated .jujurc file and I do not think there will be in the future as the main goal is to keep juju simple to use and, I guess, a dedicated configuration file would keep overhead growing.

Thanks about your comment about this project ;)
Filippo

**Comment by ka223** [comment]
@fsquillace 
is the ~/junest/etc/profile file loaded automatically ?

I tried to set the variable in this file "PS1='user@junest>'", but it is not set after starting junest.

**Comment by fsquillace** [comment]
Strange, I just tried and it works for me.

Are you sure the PS1 does not get overriden?

**Comment by fsquillace** [comment]
Have you tried `~/.bash_profile` instead?

**Comment by ka223** [comment]
Yes, I tried. Manually loading the file with ". /etc/profile" works in user mode.
Junest is a "fresh" install, just a few upgrades loaded with pacman.

**Comment by ka223** [comment]
@fsquillace 
The /etc/profile file from junest is loaded, but my host bash_aliases is loaded after that.

**Comment by ka223** [comment]
@fsquillace can I change the order?
Thanks

**Comment by fsquillace** [comment]
I guess that does no depend on junest but it is the way bash program is configured in Arch Linux. I suggest you to look at `/etc/bash.bashrc` and `man bash`.
